// .reference/examples/svelte/frontend/src/App.svelte
<script>
  import { onMount } from "svelte";

  let bridge = $state("checking...");

  onMount(() => {
    bridge = window.zero ? "available" : "not enabled";
  });
</script>

<main>
  <p class="eyebrow">zero-native + Svelte</p>
  <h1>App</h1>
  <p class="lede">A Svelte frontend running inside the system WebView.</p>
  <div class="card">
    <span>Native bridge</span>
    <strong>{bridge}</strong>
  </div>
</main>

// .reference/examples/react/frontend/src/App.tsx
import { useEffect, useState } from "react";

export default function App() {
  const [bridge, setBridge] = useState("checking...");

  useEffect(() => {
    setBridge((window as any).zero ? "available" : "not enabled");
  }, []);

  return (
    <main>
      <p className="eyebrow">zero-native + React</p>
      <h1>React</h1>
      <p className="lede">A React frontend running inside the system WebView.</p>
      <div className="card">
        <span>Native bridge</span>
        <strong>{bridge}</strong>
      </div>
    </main>
  );
}
